@startuml
entity "Restaurante" as restaurante {
    + id: String
    + nome: String
    + logradouro: String
    + numero: Integer
    + bairro: String
    + cep: String
    + cozinha: String
    + local: Point
}
 
entity "Prato" as prato {
    + id: String
    + nome: String
    + preco: Float
    + descricao: String
}
 
entity "Entrada" as entrada {
    + id: String
    + nome: String
    + preco: Float
    + descricao: String
}
 
entity "Principal" as principal {
    + id: String
    + nome: String
    + preco: Float
    + descricao: String
}
 
entity "Sobremesa" as sobremesa {
    + id: String
    + nome: String
    + preco: Float
    + descricao: String
}
 
restaurante --{ prato : "id_restaurante" -> "id"
prato --{ entrada : "pratoId" -> "id"
prato --{ principal : "pratoId" -> "id"
prato --{ sobremesa : "pratoId" -> "id"
@enduml